# Generated by Django 4.1.5 on 2023-01-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0002_bibliotheque_document_membre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_shelters.shelter'),
        ),
    ]
