# Generated by Django 4.1.5 on 2024-03-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0003_alter_dog_shelter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bibliotheque',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Membre',
        ),
    ]
