# Generated by Django 4.1.5 on 2024-03-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0005_rename_shelter_classe_rename_location_classe_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.TextField()),
                ('dateNaiss', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_shelters.classe')),
            ],
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
